CREATE TABLE
	IF NOT EXISTS "users" (
		"id" VARCHAR(255) PRIMARY KEY NOT NULL,
		"full_name" VARCHAR(255) NOT NULL,
		"username" VARCHAR(255) UNIQUE NOT NULL,
		"phone_number" VARCHAR(255) NOT NULL UNIQUE,
		"email_address" VARCHAR(255) NOT NULL UNIQUE,
		"avatar_url" VARCHAR(255) NULL,
		"banned" BOOLEAN NOT NULL DEFAULT false,
		"locked" BOOLEAN NOT NULL DEFAULT false,
		"created" TIMESTAMPTZ NOT NULL DEFAULT NOW (),
		"updated" TIMESTAMPTZ NOT NULL DEFAULT NOW ()
	);

CREATE TABLE
	IF NOT EXISTS "accounts" (
		"id" VARCHAR(255) PRIMARY KEY NOT NULL,
		"user_id" VARCHAR(255) NOT NULL,
		"password" VARCHAR(255) NOT NULL,
		"created" TIMESTAMPTZ NOT NULL DEFAULT NOW (),
		"is_active" BOOLEAN NOT NULL DEFAULT false,
		"updated" TIMESTAMPTZ NOT NULL DEFAULT NOW (),
		FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
	);

CREATE TABLE
	IF NOT EXISTS "phones" (
		"id" VARCHAR(255) PRIMARY KEY NOT NULL,
		"user_id" VARCHAR(255) NOT NULL,
		"phone" VARCHAR(255) UNIQUE NOT NULL,
		"primary" BOOLEAN NOT NULL DEFAULT false,
		"verified" BOOLEAN NOT NULL DEFAULT false,
		"created" TIMESTAMPTZ NOT NULL DEFAULT NOW (),
		"updated" TIMESTAMPTZ NOT NULL DEFAULT NOW (),
		CONSTRAINT "phones_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
	);

CREATE TABLE
	IF NOT EXISTS "emails" (
		"id" VARCHAR(255) PRIMARY KEY NOT NULL,
		"user_id" VARCHAR(255) NOT NULL,
		"email" VARCHAR(255) UNIQUE NOT NULL,
		"primary" BOOLEAN NOT NULL DEFAULT false,
		"verified" BOOLEAN NOT NULL DEFAULT false,
		"created" TIMESTAMPTZ NOT NULL DEFAULT NOW (),
		"updated" TIMESTAMPTZ NOT NULL DEFAULT NOW (),
		CONSTRAINT "emails_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
	);
