services:
    postgres:
        container_name: ${DB_NAME}
        image: postgres:latest
        environment:
            TZ: "GMT-3"
            PGTZ: "GMT-3"
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            PG_DATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        volumes:
            - master:/var/lib/postgresql/data
volumes:
    master:
